name: Test

on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest, macos-11, macos-latest, windows-2019, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
    - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9
      with:
        go-version: 1.17.x
    - name: Test
      run: go test ./...
