name: Test

on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest, macos-11, macos-latest, windows-2019, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247
    - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
      with:
        go-version: 1.17.x
    - name: Test
      run: go test ./...
