name: Test

on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-10.15, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
    - uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613
      with:
        go-version: 1.17.x
    - name: Test
      run: go test ./...
